[package]
name = "capi"
version = "0.6.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "jemalloc_pprof"

[dependencies]
libc.workspace = true
util.workspace = true
anyhow.workspace = true
tempfile.workspace = true
mappings.workspace = true
errno.workspace = true
